ALTER TABLE "CheckIn" ADD COLUMN IF NOT EXISTS "firstSmsSentAt" TIMESTAMP(3);
ALTER TABLE "CheckIn" ADD COLUMN IF NOT EXISTS "secondSmsSentAt" TIMESTAMP(3);
ALTER TABLE "CheckIn" ADD COLUMN IF NOT EXISTS "firstAlertUnresponsiveAt" TIMESTAMP(3);
ALTER TABLE "CheckIn" ADD COLUMN IF NOT EXISTS "secondAlertUnresponsiveAt" TIMESTAMP(3);
ALTER TABLE "CheckIn" ADD COLUMN IF NOT EXISTS "primaryContactSmsSentAt" TIMESTAMP(3);
